import typing

from faker import Faker

from apps.contact_generator.models import models
from apps.contact_generator.models import Contact


def generate_of_contacts(amount: int = 100,
                         is_mark_as_autogenerated: bool =
                         False) -> typing.Iterator[models.Contact]:
    fake = Faker
    for _ in range(amount):
        yield models.Contact(
            name=fake.name(),
            number=fake.phone_number(),
            is_mark_as_autogenerated=is_mark_as_autogenerated,
        )
