# Generated by Django 4.1.5 on 2023-02-22 07:45

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    replaces = [
        ("contact_generator", "0001_initial"),
        ("contact_generator", "0002_contact_is_auto_generated"),
        ("contact_generator", "0003_alter_contact_number"),
        ("contact_generator", "0004_alter_contact_number"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("number", phone_field.models.PhoneField(blank=True, help_text="Contact phone number", max_length=31)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_auto_generated", models.BooleanField(default=False)),
            ],
        ),
    ]
