# Generated by Django 4.1.5 on 2023-02-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_auto_generated",
            field=models.BooleanField(default=False),
        ),
    ]
