# Generated by Django 4.1.5 on 2023-02-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_generator", "0002_contact_is_auto_generated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="number",
            field=models.IntegerField(),
        ),
    ]
