# Generated by Django 4.1.5 on 2023-03-04 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_generator", "0001_squashed_0004_alter_contact_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nationality",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="contact",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nationality",
                to="contact_generator.nationality",
            ),
        ),
    ]
