# Generated by Django 4.1.5 on 2023-03-04 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_generator", "0005_nationality_contact_nationality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="nationality",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nationality",
                to="contact_generator.nationality",
            ),
        ),
    ]
