# Generated by Django 4.1.7 on 2023-03-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_generator", "0007_contact_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="avatar",
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to="contact/avatar"),
        ),
    ]
